"""Remove the hand-maintained ## Files section from chapter README.md files.

The ## Files section in each chapter README listed exercises, flashcard decks,
and reference files. This information is now auto-generated by build_mkdocs.py
into exercises.md and flashcards.md listing pages. The hand-maintained section
is therefore redundant and is removed here.

Pattern removed:
    The --- rule immediately before ## Files, the ## Files section itself
    (including all ### subsections), through the closing --- rule that ends it.
    The closing --- is preserved so it continues to separate the lesson header
    (byline, etc.) from the lesson body.

Usage:
    python scripts/remove_readme_files_sections.py [--dry-run] [--course bbh|bbg|bba|all]
"""

import argparse
import re
import sys
from pathlib import Path

ROOT = Path(__file__).parent.parent
LESSONS = ROOT / "data" / "lessons"

# Matches:  \n---\n\n## Files<anything (non-greedy)>\n---\n
# Replaces with: \n\n---\n   (keeps the closing ---, adds blank line before it)
_FILES_SECTION = re.compile(
    r"\n---\n\n## Files\b.*?\n---\n",
    re.DOTALL,
)

COURSE_DIRS = {
    "bbh": LESSONS / "bbh",
    "bbg": LESSONS / "bbg",
    "bba": LESSONS / "bba",
}


def process_file(path: Path, dry_run: bool) -> bool:
    """Remove ## Files section from one README.md. Returns True if changed."""
    original = path.read_text(encoding="utf-8")
    fixed, n = _FILES_SECTION.subn("\n---\n", original)
    if n == 0:
        return False
    if not dry_run:
        path.write_text(fixed, encoding="utf-8")
        print(f"  Fixed: {path.relative_to(ROOT)}")
    else:
        print(f"  [dry-run] Would fix: {path.relative_to(ROOT)}")
    return True


def main() -> None:
    parser = argparse.ArgumentParser(
        description=__doc__,
        formatter_class=argparse.RawDescriptionHelpFormatter,
    )
    parser.add_argument(
        "--course", choices=["bbh", "bbg", "bba", "all"], default="all",
        help="Which course to process (default: all)",
    )
    parser.add_argument(
        "--dry-run", action="store_true",
        help="Report what would change without writing files",
    )
    args = parser.parse_args()

    courses = ["bbh", "bbg", "bba"] if args.course == "all" else [args.course]
    total = 0
    for course in courses:
        base = COURSE_DIRS[course]
        if not base.exists():
            print(f"  [skip] {base} does not exist")
            continue
        for readme in sorted(base.rglob("README.md")):
            # Only process chapter-level READMEs (ch*/README.md)
            if readme.parent.parent != base:
                continue
            if process_file(readme, args.dry_run):
                total += 1

    action = "Would update" if args.dry_run else "Updated"
    print(f"\n{action} {total} README file(s).")
    sys.exit(0)


if __name__ == "__main__":
    main()
